name: First action

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      -name: step one
        run: date
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      -name: step one
        run: date
  job3:
    name: Third job
    runs-on: macos-latest
    steps:
      -name: step one
        run: date
  job4:
    name: Dependencies job
    needs: [job1, job2, job3]
    runs-on: ubuntu-latest
    steps:
      -name: Final step
        run: echo "you are done the mission !"

