name: First action

on:
  push:
    paths:
      - '**.md'

jobs:
  ubuntu:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - run: date
  windows:
    name: Second job
    runs-on: windows-latest
    steps:
    - run: date
  macos:
    name: Third job
    runs-on: macos-latest
    steps:
    - run: date
  depends:
    name: Dependencies job
    needs: [ubuntu, windows, macos]
    runs-on: ubuntu-latest
    steps:
    - run: echo "you are done the mission !"

